
name: Flutter+Android+Firebase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_APK_FireBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - run: flutter pub get
      - run: flutter build apk --debug

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-Android
          path: build/app/outputs/apk/debug/app-debug.apk
      #        path: build-output/ios/checkingcicd.ipa
      #      - uses: ncipollo/release-action@v1
      #        with:
      #          artifacts: "build/app/outputs/apk/debug/app-debug.apk"
      #          tag: v1.0.${{ github.run_number }}
      #          token: ${{ secrets.TOKEN }}

      - name: Upload APK Artifact to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/apk/debug/app-debug.apk
#          releaseNotes: v1.0.0
#          releaseNotesFile: v1.0.0